version: '3.5'

services:

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: alexnv
      POSTGRES_PASSWORD: alexnvpass
      POSTGRES_DB: walletdb
      POSTGRES_INITDB_ARGS: "--data-checksums"
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5439:5432

  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
